### ISSUE TITLE
document matplotlib patterns in appendix

### ISSUE THREAD

**Issue by hancush** [datamade/data-analysis-guidelines#13]
our current forays into plotting with python have been functional, but slightly disorganized. let's assess our current tooling (some [`pandas.DataFrame.plot`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html) shorthand, some use of the [`matplotlib.pyplot`](https://matplotlib.org/api/pyplot_summary.html#the-pyplot-api) api), as well as some alternatives, including but not limited to: [`altair`](https://altair-viz.github.io/getting_started/overview.html), [`ggplot`](http://ggplot.yhathq.com/) (for python), ["object-oriented" `matplotlib`](https://matplotlib.org/api/pyplot_summary.html#the-object-oriented-api), and [`seaborn`](https://seaborn.pydata.org/index.html).

once we've done our assessment, let's pick the one we like best, and commit that to the toolkit canon for all.

**Comment by hancush** [comment]
### hc notes

here's a nice breakdown of [some popular options for charting in python](https://blog.modeanalytics.com/python-data-visualization-libraries/).

i think the reason that our current approach to charting is so ugly has a lot to do with using the shorthand plotting api from `pandas` rather than using the `matplotlib` (mpl) api. moving forward, i think i would be comfortable saying we will not use `pandas` shorthand (or limit use of said shorthand); it obscures away some very important things about mpl – i.e., there’s actually an underlying structure – such that it impedes understanding, and too often behaves counter to expectations.

i'm going to spend some time [with the mpl documentation](https://matplotlib.org/tutorials/index.html).

if we're very unhappy with mpl, i'd cast my lot for [`seaborn`](https://seaborn.pydata.org/index.html
). it provides a higher level api for common statistical charts, and the output looks a lot nicer, too. it's also built on top of mpl, so the syntax is simplified but not wholly different, which makes it seem easier to learn to me.

regardless of the tooling we choose, i'd like to make a conscious effort to actually learn what i'm doing, rather than scouring stackoverflow for hacks.

**Comment by fgregg** [comment]
From this person on twitter: https://twitter.com/ktrst/status/985968491852369921

- https://matplotlib.org/tutorials/introductory/lifecycle.html
- https://realpython.com/python-matplotlib-guide/
- https://dev.to/skotaro/artist-in-matplotlib---something-i-wanted-to-know-before-spending-tremendous-hours-on-googling-how-tos--31oo

**Comment by hancush** [comment]
we've decided we like `matplotlib`. to wrap this in a bow, i'd like to add an appendix with charting patterns (and anti-patterns) to this repo.
